### ISSUE TITLE
Does it work at Swift 3.2 and/or Swift 4.0 ?

### ISSUE THREAD

**Issue by igordeoliveirasa** [sabirvirtuoso/Mockit#14]
Does it work at Swift 3.2 and/or Swift 4.0 ?

**Comment by sabirvirtuoso** [comment]
No not yet. Need to update.

**Comment by sabirvirtuoso** [comment]
@igordeoliveirasa please do not hesitate to update for newer versions of Swift and send me a pull request :)

**Comment by chriet** [comment]
I send a pr for 4.0 :)

**Comment by mericksters13** [comment]
Hi, I sent a pr for 4.0 since @chriet pr failed on CI

**Comment by chriet** [comment]
markcbd pr has been merged, can we do a release on cocoapods?
